language: c
sudo: false # only for faster builds
compiler:
   -clang
   -gcc
script:
  - clang -coverage -O0 pattern.c -o pattern
  - ./pattern
  - clang -coverage -O0 pavan.c -o pavan
  - ./pavan
  - clang -coverage -O0 basu.c -o basu
  - ./basu
  - clang -coverage -O0 anand.c -o anand
  - ./anand



